---
title: "Inference for the Naomi model: informal discussion"
description: |
  A summary, some potentially useful takeaways, and reflections on the paper "Fast approximate Bayesian inference of HIV indicators using PCA adaptive Gauss-Hermite quadrature"
author:
  - name: Adam Howes
    url: {}
date: 2025-11-16
preview: figB.png
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    self_contained: false
bibliography: citations.bib
---

## Background and motivation

[Naomi](https://naomi.unaids.org/login) is a small-area estimation model used to produce district-level estimates of HIV indicators.
The model "synthesises" or "triangulates" data from multiple sources.
To do this, it uses a fairly complex spatio-temporal hierarchical Bayesian model, which requires [quite a few pages]((https://athowes.github.io/thesis/naomi-aghq-appendix.html#naomi-math) to describe.

The model is used to produce estimates by over 35 countries in annual workshops facilitated by UNAIDS.
For this reason, it's important that the model can be run quickly and reliably, and on standard hardware.

In the @rue2009approximate RSS Discussion paper, Hans Skaug proposes using automatic differentiation to implement a fast, flexible and easy to use approach to INLA.

## Extended latent Gaussian models



## Scaling up the hyperparameter grid

Adaptive Gauss-Hermite quadrature is a smart method for integrating with respect to densities which are close to being Gaussian.

## Comparing inferences

## Statistical software

```{r echo=FALSE}
tweetrmd::tweet_embed("https://twitter.com/strengejacke/status/1733051326970417260")
```

# Other

## Personal reflection

Finishing this paper has been a long and winding process.
I started this project at the beginning of my PhD, and spent a lot of time quite lost.
I don't think I would have got to the end of it without [Alex Stringer](https://www.alexstringer.ca/), so as well as thanking him, I'd like to thank [Tim Lucas](https://timcdlucas.github.io/) for putting us in touch.
I think visiting the University of Waterloo in-person last fall was also crucial, so thank you to the department there for being so welcoming, as well as the [StatML CDT](https://statml.io/) for providing funding^[No thanks to you, Kitchener-Waterloo rental market, sorry.].
